<a href="https://colab.research.google.com/github/srusti897/Neural-Network/blob/main/Tensors_and_their_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
t = torch.tensor([1, 2, 3])
print(t)

tensor([1, 2, 3])


In [2]:
import torch
# create tensor
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
# basic operations
print(a + b)      # addition
print(a - b)      # subtraction
print(a * b)      # multiplication
print(a / b)      # division
print(torch.sum(a))   # sum of elements
print(a.shape)        # shape of tensor

tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])
tensor(6)
torch.Size([3])


In [3]:
import torch
# 2×3 tensor with zeros
zeros_tensor = torch.zeros(2, 3)
# 2×3 tensor with ones
ones_tensor = torch.ones(2, 3)
print(zeros_tensor)
print(ones_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [4]:
import torch
lst = [[1, 2, 3], [4, 5, 6]]
# Convert list to tensor
t = torch.tensor(lst)
print(t)
print("Shape:", t.shape)
print("Data type:", t.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])
Data type: torch.int64


In [8]:
import torch
# Create a tensor of size 12
t = torch.arange(12)
print(t)
# Reshape into (3, 4)
reshaped = t.reshape(3, 4)
print(reshaped)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [9]:
import torch
t = torch.tensor([[1, 2, 3], [4, 5, 6]])
# Find rank (number of dimensions)
rank = t.ndim
print("Rank:", rank)

Rank: 2


In [10]:
import torch
t = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
second_row = t[1]
third_column = t[:, 2]
print("Second row:", second_row)
print("Third column:", third_column)

Second row: tensor([4, 5, 6])
Third column: tensor([3, 6])


In [11]:
import torch
a = torch.randn(3, 4)
b = torch.randn(4, 2)
result = torch.matmul(a, b)
print(result)
print("Result shape:", result.shape)

tensor([[-1.5476,  0.3686],
        [-1.4165, -1.0197],
        [ 3.2082, -4.0485]])
Result shape: torch.Size([3, 2])


In [12]:
import torch
t = torch.tensor([[[1, 2],
                   [3, 4]],
                  [[5, 6],
                   [7, 8]]])
# Transpose the last two dimensions
t_transpose = t.transpose(1, 2)
print(t_transpose)

tensor([[[1, 3],
         [2, 4]],

        [[5, 7],
         [6, 8]]])


In [13]:
import torch
x = torch.tensor([2.0, 1.0, 0.1])
# Softmax implementation
exp_x = torch.exp(x)              # exponentiation
softmax = exp_x / torch.sum(exp_x)  # divide by sum
print(softmax)

tensor([0.6590, 0.2424, 0.0986])


In [14]:
import torch
t = torch.tensor([10.0, 20.0, 30.0, 40.0])
# Normalize between 0 and 1
t_min = torch.min(t)
t_max = torch.max(t)
normalized = (t - t_min) / (t_max - t_min)
print(normalized)

tensor([0.0000, 0.3333, 0.6667, 1.0000])


In [15]:
import torch
x = torch.tensor(3.0, requires_grad=True)
# Tensor operation
y = x * x + 2 * x   # y = x² + 2x
# Compute gradient
y.backward()
print(x.grad)

tensor(8.)


In [16]:
import torch
# Image tensor with shape (H, W, C)
img = torch.randn(64, 64, 3)
# Convert to (C, H, W)
img_chw = img.permute(2, 0, 1)
print(img_chw.shape)

torch.Size([3, 64, 64])


In [17]:
import torch
t = torch.tensor([1, 5, 3, 8, 2])
# Mask elements greater than 3
masked = t[t > 3]
print(masked)

tensor([5, 8])


In [18]:
import torch
# Original tensor
t = torch.arange(6)          # [0,1,2,3,4,5]
# 1. view - changes shape, shares memory
t_view = t.view(2, 3)
print("View:\n", t_view)
# 2. reshape - changes shape, may copy if needed
t_reshape = t.reshape(2, 3)
print("Reshape:\n", t_reshape)
# 3. transpose - swaps dimensions of 2D tensor
t2d = torch.tensor([[1, 2, 3],
                    [4, 5, 6]])
t_transpose = t2d.transpose(0, 1)
print("Transpose:\n", t_transpose)

View:
 tensor([[0, 1, 2],
        [3, 4, 5]])
Reshape:
 tensor([[0, 1, 2],
        [3, 4, 5]])
Transpose:
 tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [19]:
import torch
t = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
# Transpose tensor (not contiguous)
t_trans = t.transpose(0, 1)
print(t_trans.is_contiguous())  # False
# Make it contiguous
t_cont = t_trans.contiguous()
print(t_cont.is_contiguous())   # True

False
True


In [20]:
import torch
# Example tensors
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])
# Step 1: Compute dot product
dot = torch.sum(a * b)
# Step 2: Compute norms
norm_a = torch.sqrt(torch.sum(a * a))
norm_b = torch.sqrt(torch.sum(b * b))
# Step 3: Cosine similarity
cos_sim = dot / (norm_a * norm_b)
print("Cosine Similarity:", cos_sim)

Cosine Similarity: tensor(0.9746)
