<a href="https://colab.research.google.com/github/srusti897/Neural-Network/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [25]:
# This will be an int32 tensor by default; see "dtypes" below.
rank_0 = tf.constant(4, 5, 6)
print(rank_0)

tf.Tensor([4 4 4 4 4 4], shape=(6,), dtype=int16)


In [14]:
# Let's make this a float tensor.
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [34]:
# If you want to be specific, you can set the dtype (see below) at creation time
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6],
                             [3, 3]])
print(rank_2_tensor) # by default it will create data type as integer

rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6],
                             [3, 3]], dtype=tf.float16) # data type is mentioned
print(rank_2_tensor)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [3 3]], shape=(4, 2), dtype=int32)
tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]
 [3. 3.]], shape=(4, 2), dtype=float16)


In [5]:
# There can be an arbitrary number of
# axes (sometimes called "dimensions")
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [35]:
np.array(rank_2_tensor)

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [3., 3.]], dtype=float16)

In [36]:
rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [3., 3.]], dtype=float16)

In [42]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2], dtype=tf.int32)`

print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n") # tf.matmul(a, b) is done by taking each row of a, multiplying it with each column of b, and summing the products to form each output element.
print(tf.matmul(a, b), "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [40]:
a = tf.ones([2, 2], dtype = tf.int32) #by default it will take as float
print(a)

tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)


In [43]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

# Find the largest value
print(tf.reduce_max(c)) # returns the largest value in tensor c
# Find the index of the largest value
print(tf.math.argmax(c)) # returns the index of maximum value
# Compute the softmax
print(tf.nn.softmax(c)) # converts the values in c to probabilities

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


In [45]:
tf.convert_to_tensor([11, 23, 44])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 23, 44], dtype=int32)>

In [47]:
tf.reduce_min([11,22,33]) # minimum value
tf.reduce_max([11,22,33]) # maximum value

<tf.Tensor: shape=(), dtype=int32, numpy=33>